### ISSUE TITLE
Is Fenix 3 still in development?

### ISSUE THREAD

**Issue by manngo** [coreybutler/fenix#103]
All the information I can find is dated, so I wondered whether this is still happening … ?

**Comment by coreybutler** [comment]
Yes - we got wrapped up in several paid client engagements for a few months... the last of which ends next week. @gbdrummer will be focusing on Fenix full time starting then & I'll be diving in a few days later.

There are only two outstanding issues preventing a general release:

- The **Windows installer** is complex and I made it about 80% of the way through before the client engagement consumed my time. Many improvements have been made to the underlying libs while we were wrapped up, so hopefully this will be a quick fix.
- [Fenix Imports](https://docs.fenixwebserver.com/remote-imports-and-fenix-badges.html) (new in v3) relied on the Google URL shortener, which was deprecated. We will be replacing it.

 Aside from the aforementioned imports, macOS version is pretty much ready to go, downloadable at https://preview.fenixwebserver.com.

**Comment by manngo** [comment]
Thanks for your reply. I’m happy enough with version 2, but I was more interested in what the future held. I can now happily use it and recommend it to my students.

If you can spare a few minutes to clarify this on your website, I think a few others would also be relieved.

Thanks again …

**Comment by coreybutler** [comment]
@manngo - We'll be launching the preview site as the main site in a few days, because you're right, we've been silent for far too long.

If you're part of an accredited educational program, let me know. We're working with a few EDU programs to help offer academic licensing for the PRO version.

**Comment by darklinki** [comment]
Can´t wait for the windows version 👍  
Hope Fenix will receive some kind of cloud sync for multiple dev environments.

**Comment by coreybutler** [comment]
@darklinki - There have been enough challenges with the available Windows install platforms available that we decided to make our own. So, that's in progress as I write this.

We are working on a rather extensive collaboration system for Fenix PRO & TEAM editions (commercial). We're still assessing all of the options for true syncing, but it is on the roadmap. At the moment, we have a remote imports system (see docs.fenixwebserver.com) that allows direct imports from Github/BitBucket/etc, but it's not part of what we consider "syncing". If you have feedback/requests, we'd love to hear about it as we finalize this part of the roadmap.

---

For everyone who comes across this thread, we're back to working on Fenix and the underlying tech, with an emphasis on getting v3.0.0 launched ASAP (we're extremely frustrated with the delays). We took some time to do contract work in an effort to fund proper development. That said, Fenix will be an open core app with commercial offerings. You can see the tentative breakdown of free vs commercial features at http://preview.fenixwebserver.com.

**Comment by coreybutler** [comment]
Oh - side note... I  built a Fenix Chrome extension the other night. You'll be able to immediately navigate to sites directly from Chrome. More details to come when Fenix 3.0.0 GA is released.

**Comment by Mr-Sloth** [comment]
Any news how long the windows version will take?

**Comment by coreybutler** [comment]
@Mr-Sloth - We've completed the Windows installer for 3.0.0. We've been hung up on the autoupdate service, which is the only reason we haven't made a formal GA release. Long story short, none of the autoupdate platforms support both pkg (macOS) and custom NSIS builds _with CLI utilities_. Two nights ago, @gbdrummer and I made the decision to stop putting so much attention on the autoupdate system so we can get the full Windows/macOS releases out the door. Instead of autoupdates, we will be providing a notification system to let users know when new versions are available for download. That way this horribly long wait can end.

I'm wrapping up a client contract this week, so we're hopeful to have the notification system done next week and a formal release announcement shortly thereafter.

**Comment by Mr-Sloth** [comment]
@coreybutler Thanks for the information, just to inform you on the Fenix 3 website the GitHub link refers to author.io. I think it would be helpful if it forwards to this page.

**Comment by coreybutler** [comment]
hrm, it should be forwarding to https://preview.fenixwebserver.com. That's the new beta release.

BTW - we completed everything. It will realistically be a little while longer though, because SXSW is about to start and I am in the middle of all that. We're cleaning up the docs and putting together some examples of the new stuff before a GA release on both Windows and Mac.

**Comment by coreybutler** [comment]
We're still calling it a "release candidate", but it's done. At this point, the versioning is just so we can fix any initial bugs before calling it a GA release.

We've been using it/testing internally for a considerable amount of time now. https://github.com/coreybutler/fenix/tree/3.0.0-rc.13
