### ISSUE TITLE
Pages with SQLite3

### ISSUE THREAD

**Issue by hajczek** [coreybutler/fenix#107]
Hi,

I want to use local server Fenix on Windows system for the page, which is made with using PHP and database SQLite3. But when I want to open this page by this server, then Fenix hangs and nothing can be done... Even closing Fenix is not possible ...
What reason can be for this behavior? 
Thanks for every answer.

**Comment by coreybutler** [comment]
Fenix is a _static_ web host, so it won't work with PHP. Fenix 2 and the [Fenix 3 Preview for macOS](https://preview.fenixwebserver.com) are both designed for use with the [JAM stack](https://medium.com/memory-leak/the-jamstack-its-pretty-sweet-e0834e4e6bb7). We've talked about adding support for dynamic languages like PHP, but the amount of work required to make that happen is substantial enough to build a separate application (which would have to be commercial/paid).

I'm not sure why Fenix wouldn't close. Is it just hanging? What happens when you force-quit (through Task Manager)?

**Comment by hajczek** [comment]
Thanks for the answer!
Now I understand, why this is not working for this application ...
So, when I have open this application in Fenix then everything in Fenix stopped working - it is hanging. Nothing is clickable or hover on elements is not working... And close by option 'Close window' is not working too. Then I must restart the computer to close Fenix ...
I think this is happening because the application which is run in this server is wrong ...

**Comment by coreybutler** [comment]
I see. It does sound like Fenix may be getting hung up on the app. That should not happen in Fenix 3 since the UI runs in a separate process. 

You mentioned you're on Windows. I happen to be working on the Windows installer for Fenix 3 _right now_. There are a few other things we need to wrap up before a general release, but we're anticipating it all to be done before the end of the month. That still won't help you run a PHP app, but Fenix 3 is vastly superior to Fenix 2 for JAM stack apps. I'll post a link here when the Windows installer is released.

**Comment by hajczek** [comment]
Thanks for information.
I will be waiting for version 3 :)

**Comment by coreybutler** [comment]
v3 is available at https://github.com/coreybutler/fenix/tree/3.0.0-rc.13
