### ISSUE TITLE
Why Fenix is taking screenshots?

### ISSUE THREAD

**Issue by iamsamsaul** [coreybutler/fenix#112]
Hi there,

When I start a webserver using Fenix, the logs show that it's taking screenshots. I was curious why the software is automatically taking screenshots.

[7/3/2019 6:55:13 PM] Server started on port 80.
[7/3/2019 6:55:18 PM] Screenshot captured.
[7/3/2019 6:55:21 PM] Screenshot captured.

Please elaborate.

Thanks & Regards,

Sam Saul

**Comment by coreybutler** [comment]
Fenix 2 takes a screenshot of the website so you can see your site "at a glance" from the list.

It's a little difficult to see, but the screenshot below has a thumbnail of each site:

![banner_device](https://user-images.githubusercontent.com/770982/60623790-1f334b80-9da9-11e9-8b61-f0de07c5d724.png)

Sometimes you end up with alot of sites, and it's easy to forget what is what (sometimes). This feature was designed to prevent that scenario. However; this feature has been pulled out of Fenix 3, since there wasn't much feedback on it.

**Comment by iamsamsaul** [comment]
Thanks for your reply!
