### ISSUE TITLE
demo will not open via fenix

### ISSUE THREAD

**Issue by gracemcmenamin** [coreybutler/fenix#124]
I am an oracle employee and am not able to open a live demo via fenix or the link that the application leads to.

**Comment by coreybutler** [comment]
It appears the SSH tunneling service (localtunnel.me) went offline. This is a third party service I do not maintain. This happens on occasion in January when they update their TLS/SSL certificate. I suspect this issue will be resolved shortly.

For any companies/people who depend on Fenix for work, I am open to discussing support contracts or hosting a private tunneling service. We have long considered running an affordable tunneling service specifically designed for Fenix.

I'm closing since this is an upstream issue that I believe will be resolved shortly. If there is any interest in the aforementioned service, please comment here and I will setup a contact form.
