### ISSUE TITLE
Read gzip files

### ISSUE THREAD

**Issue by pepeyola** [coreybutler/fenix#19]
Is there any way to read gzip files from the localhost?

**Comment by geoff** [comment]
I came here to ask about the same. Even a temporary kludge method would be nice to test gzip compression functionality in local dev environment for a static website generator.

**Comment by coreybutler** [comment]
This is an option in Fenix 3.

Preview:

![image](https://cloud.githubusercontent.com/assets/770982/17311888/314f63e0-5814-11e6-8bba-f26c19e2520c.png)

![image](https://cloud.githubusercontent.com/assets/770982/17311926/75dbd89a-5814-11e6-978d-420b916dd01a.png)

Closing since this is in the new version (release coming soon).
