### ISSUE TITLE
A long folder path displays poorly

### ISSUE THREAD

**Issue by cfjedimaster** [coreybutler/fenix#23]
See the path int he top server. It breaks at the space, which is ok I guess, but there isn't enough vertical space to display it properly.

![image](https://cloud.githubusercontent.com/assets/393660/3222975/527a72aa-f01d-11e3-8bee-79678ef58f14.png)

**Comment by coreybutler** [comment]
Better late than never. This is fixed in the totally new UI in Fenix 3 (we're getting close to a release).

Preview:

![image](https://cloud.githubusercontent.com/assets/770982/17311828/cd6adfd0-5813-11e6-9771-8e9bb59cf6cc.png)

(This is completely responsive, right down to font size responsiveness).
