### ISSUE TITLE
support for pushstate domains

### ISSUE THREAD

**Issue by mazondo** [coreybutler/fenix#29]
Would love the ability to set a default file (perhaps default to index.html) for 404 requests.  Would make single page webapp testing easier.  Right now I use a quick sinatra app for serving my apps that require pushstate support.

**Comment by coreybutler** [comment]
Fenix 3 got some new features that I believe will make this possible. First, we'll be shipping a directory with an HTML page for every status code. It's possible to modify those, but a better way will be specifying your own error files directory as shown below:

![image](https://cloud.githubusercontent.com/assets/770982/17371603/14a68f68-5966-11e6-9340-e5a3128cf50e.png)

What's shown above is a global setting applicable to every server. There is also the ability to specify default files like `index.html`, `default.htm`, etc. at a server by server level. 

![image](https://cloud.githubusercontent.com/assets/770982/17371698/7e0782dc-5966-11e6-84fd-e298ca849d32.png)

I'm closing this since it's already built into Fenix 3.
