### ISSUE TITLE
Log Viewing Improvements

### ISSUE THREAD

**Issue by calendee** [coreybutler/fenix#40]
It would be good if the log viewer could be opened wider.  Even better, being able to save the log to a file or copy from it would help tremendously.

**Comment by coreybutler** [comment]
Enhanced screen logging is working in Fenix 3 (coming soon). It also logs to a physical file when a log path is specified. The screenshot below may change a little by release time.

![image](https://cloud.githubusercontent.com/assets/770982/17311736/2ac8718e-5813-11e6-9548-75cc75689d64.png)

Closing since this is in the new version.
