### ISSUE TITLE
localtunnel.me proxy dies after short period

### ISSUE THREAD

**Issue by rickdog** [coreybutler/fenix#64]
After I start a localtunnel.me server it dies after a few minutes, is there any way to debug this?  I can pull a few files from the proxy but it eventually quits displaying: 
localtunnel error: no active client for '_whatever_'

**Comment by coreybutler** [comment]
This has to do with localtunnel.me killing sessions. Since it's a 3rd party free service, there's nothing Fenix can offer in the way of debugging, but you might be able to reach out to the localtunnel.me guys. It appears like this happens more often during times when localtunnel.me is under higher load.

FWIW - I am working on an alternative SSH tunneling component for version 3.0 (which I happen to be working on this very second). I am looking at alternative tunneling services for the open source version, and there is a very strong likelihood I'll offer a commercial service for more stable/dedicated use. No ETA on that yet.

**Comment by rickdog** [comment]
thanks for the quick response.  For some reason if I use the npm localtunnel module under io.js it's much more stable.  Shouldn't make a difference but it does.  Can you give me any other tunneling proxies other than localtunnel.com that I can check out?

**Comment by rickdog** [comment]
I looked at the ngrok server https://ngrok.com/, they are using your icon on their directory listings, are they working with you?
![ngrok](https://cloud.githubusercontent.com/assets/77186/14406551/ccbc03b8-fe70-11e5-94ea-a74e534de99a.JPG)

**Comment by coreybutler** [comment]
Fenix is currently hard-coded to use the localtunnel.me service (i.e. the push button control in the UI). You could spin up a Fenix Web Server and use ngrok to just point to the specified Fenix port.

The localtunnel client seems to have lost momentum and does present some instability... as you've experienced. I've written SSH clients in both node and Go. Right now, I'm leaning towards offloading this to Go. Go has pretty solid native SSH support, and of course this opens the door for using tools like ngrok directly from the Fenix UI.

**Comment by coreybutler** [comment]
It looks like you already implemented what I was suggesting in the Github
issues. I'm not working with Alan (ngrok author) on anything. You're seeing
the Fenix index page because ngrok is just bridging a connection straight
to your computer. The actual HTTP server is within Fenix. This is the same
way localtunnel works, so you should always see the Fenix index page
regardless of which SSH tunneling system you're using.

On Sat, Apr 9, 2016 at 4:34 PM, rickdog <notifications@github.com> wrote:

> I looked at the ngrok server https://ngrok.com/, they are using your icon
> on their directory listings, are they working with you?
> [image: ngrok]
> <https://cloud.githubusercontent.com/assets/77186/14406551/ccbc03b8-fe70-11e5-94ea-a74e534de99a.JPG>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/coreybutler/fenix/issues/64#issuecomment-207856491>
>



-- 
Corey Butler
http://www.coreybutler.com
https://www.linkedin.com/in/coreyabutler
http://twitter.com/goldglovecb
http://www.facebook.com/coreybutler

**Comment by rickdog** [comment]
already using ngrok with fenix, works great!  Supposedly the localtunnel npm client can use a server other than localclient by specifying it in the -host parameter, but I couldn't get it to work with ngrok
