### ISSUE TITLE
v3?

### ISSUE THREAD

**Issue by equinusocio** [coreybutler/fenix#74]
Any update about v3? And how download the release candidate?

**Comment by coreybutler** [comment]
We're almost done with the first round of fixes from the private beta. We'll be putting out the Mac  release candidate as soon as we can, and the Windows version will follow shortly after. If you're signed up to the [mailing list](http://fenixwebserver.com/#register), you'll receive links to these as soon as they're ready.

I've released a few screenshots throughout some of the issues in this repo as they've been completed. I also released a screenshot of v3 in [Developing Nirvana](https://www.youtube.com/watch?v=YdZv_4l4NMw&feature=youtu.be&list=PLfMzBWSH11xYaaHMalNKqcEurBH8LstB8) around the 17 minute mark, but it came out pretty blurry. It might be easier to see in the [slides](https://github.com/coreybutler/talk-developingnirvana).

I'm also working on the autoupdate service. Key feedback indicated this feature should be in place ASAP. Unfortunately, this isn't as straightforward as using the typical Electron autoupdater service. I've been in touch with some of the folks behind this project to work through it, and it is coming along nicely. I hope to have it wrapped up within the next 2 weeks.

**Comment by equinusocio** [comment]
@coreybutler Thanks!

**Comment by coreybutler** [comment]
It's been awhile since there was a status update. We're still trying to muscle through the autoupdater system. We've been forced to build our own API for this since the existing solutions don't support multiple editions of a product (Fenix 3 has a free core edition, an upcoming PRO edition, and a future Team edition). So... yet another delay. The upside is we may be able to offer this as a solution for other commercial app developers. We like the idea of being able to eliminate pain points for developers, so this is looking to be a "our pain your gain" situation.

The Mac version is ready for an RC release.... it's just blocked by the autoupdate delay. The [migration wizard](https://www.facebook.com/softwareauthor/photos/pcb.349293325456253/349292988789620/?type=3&theater) for Fenix 2 users is done, and the new Deployments service has gone through a battery of tests.

This release is pivotal, in the sense that making Fenix evergreen will allow us to push updates at a much faster rate. It feels like this release just keeps getting pushed back, but we want to make sure it's done right so there's never a long gap between releases again.

**Comment by equinusocio** [comment]
Thanks for the update.

Il gio 23 feb 2017, 18:06 Corey Butler <notifications@github.com> ha
scritto:

**Comment by coreybutler** [comment]
I've been referring a few people to this issue for updates, so here are the latest:

Fenix 3 is built on Electron. I gave a [recorded talk](https://www.youtube.com/watch?v=KsoNGVScd_c) about Electron with a live preview of Fenix Deployments (see the YouTube comments to jump to specific parts of the event).

In our steps towards general availability, we partnered up with General Assembly to expedite remaining UX research and design for the new websites, and they've been going full throttle. Some of you may even receive invitations from them to join a focus group. Our autoupdate API's are nearing completion as well. Our seemingly slow progress on this has been the result of building robust worldwide infrastructure, and we fully anticipate releasing autoupdates as a service for anyone else building desktop apps with Electron. 

We are also looking for expert contributors for an upcoming community project based on Fenix. We procured hackathonresources.com and would like to put together a template catalog for hackathon participants and students, based on Fenix deployments. Our initial goal is to provide a deployable web templates written in React/Angular/Vue/Ionic/etc. 

I've also been sidetracked with a few small client projects (remember Fenix is being bootstrapped and I still have to eat), but we are still making daily progress.

**Comment by coreybutler** [comment]
The Fenix 3 Developer Preview for macOS has shipped. It is available to mailing list subscribers. We're working on a custom Windows installer and will notify the mailing list as soon as it is ready. At this point, it will be marked as "beta". A general release will come after we're confident any issues from the beta are worked out.

**Comment by coreybutler** [comment]
If you're a macOS user, you can try out the preview (and see the new website) at https://preview.fenixwebserver.com

**Comment by coreybutler** [comment]
Closing since Fenix 3 is now available on both macOS and Windows.
