### ISSUE TITLE
Any reason it tooks more than 20 seconds to load the app?

### ISSUE THREAD

**Issue by cheahkhing** [coreybutler/fenix#75]
Hi,

I am trying to use this app for easier launch my localhost.
I normally fire up "cmd", type "http-server", all of these can be done in under 5secs.

Is it only me? or is a known issue?

**Comment by coreybutler** [comment]
The app itself takes a few moments to boot due to node-webkit (removed in 3.0.0), but servers typically boot in less than a second once the app is launched. 

What operating system are you running on?

**Comment by modulexcite** [comment]
IMHO, it also depends on the hardware fenix is running on and perhaps the configuration (@coreybutler  might be able to shed some light on this). I'm running Fenix v2 on a Windows 7 64-bit OS with 16GB Memory and an i7 Quad Core processor and it takes about ~5 seconds to start up and a few more seconds to start projects.
![2017-01-13_05-54-07](https://cloud.githubusercontent.com/assets/12729391/21927712/ea64158a-d954-11e6-93dc-7e3beacfe72c.gif)

**Comment by cheahkhing** [comment]
I am running on Win8.1 a lenovo X240 laptop, while it's just an i5 proc, definitely will be slower than @modulexcite 's pc. maybe @coreybutler is right about the node-webkit part, but with this booting speed i'll have to uninstall for now. maybe i'll wait for 3.0 and see how. Thanks guys.

**Comment by coreybutler** [comment]
Details:

The slower app startup time is due to node-webkit. It must unpack resources (think of it like unzipping a big file) before it can launch. The install process does it's best to minimize this, but there's only so much it can be optimized. This is/was a limitation of node-webkit and is one of the reasons Fenix 3 was moved to Electron. A more powerful computer can shave a little time off startup in Fenix 2.

Fenix v2 also uses send as the static web server, with some custom middleware added. This is similar to what http-server uses. However; Fenix 2 adds middleware to do things like markdown rendering, inject file browsing middleware, etc. There is no way around this in v2, and it adds about half a second of startup time. In v3, these things can be toggled on/off via a user preference screen, so users have more control over how quickly a site launches or performs. Server startup time in v3 is sub-second.

**Comment by modulexcite** [comment]
When is version 3 being released? Is there an option to download the beta version?

**Comment by coreybutler** [comment]
With luck, v3 will be released in Feb. I have a Mac-only beta available that has been in private testing. I hope to have the first public release candidate out before the end of the month.

**Comment by modulexcite** [comment]
Great thanks for all the hard work, looking forward to it.
