### ISSUE TITLE
Fenix 3 - Questions

### ISSUE THREAD

**Issue by ajmas** [coreybutler/fenix#86]
Two items:

   - Any benefit of using an installer over drag and drop installation on the Mac?
   - The link for 'Find an issue? Report it button' in the preview e-mail links to https://github.com/author.fenix-rc , which doesn't seem to display anything (blank page)

**Comment by coreybutler** [comment]
Ah geez, not sure how that typo got through. The address was supposed to be https://github.com/author/fenix-rc. Good catch.

The drag and drop (DMG) installation caused alot of problems in private testing, primarily due to insufficient permissions. Both logging and the native CLI utility require one-time permissions for setup.

**Comment by coreybutler** [comment]
Released https://github.com/coreybutler/fenix/tree/3.0.0-rc.13
