### ISSUE TITLE
Fenix as an error handler?

### ISSUE THREAD

**Issue by MrBonkeyDollax** [coreybutler/fenix#92]
Hi,

I've been looking for a small piece of software that could be setup on our servers to catch HTTP requests whilst our systems are down for maintenance. Is there any way for Fenix to, for example, send a request of 127.0.0.1:80/api/rest... to the same page it would send 127.0.0.1:80? If not, could I get a pointer on where I could make such a change to the source?

Thanks!

**Comment by coreybutler** [comment]
You may be looking for a proxy. Proxies forward requests from one server to another. We have a visual proxying solution on our roadmap for the commercial edition of Fenix 3, but at the moment, there is no support for this. There are several choices... personally, I usually end up using HAProxy or writing my own (NGINX is also a popular choice) in production environments.

Closing since this is a question & I don't want it in our work log, but I'm still happy to respond here to further clarify (if necessary).
