### ISSUE TITLE
Enable Public View doesn't work on Windows 10 - Question

### ISSUE THREAD

**Issue by cresumerjang** [coreybutler/fenix#93]
I've installed fenix on my surface which os is windows 10 pro.
Everything is okay. But __enable public view__ is does not work.
There is nothing feedback even text message.
What should I check?

**Comment by cresumerjang** [comment]
I have tried this with command line and get the same result.
only check this message "Fenix did not respond (timeout)"

**Comment by coreybutler** [comment]
This is almost certainly a problem with the tunneling service (localtunnel.me). It's been under heavy load lately, so you probably just need to wait and try again. Localtunnel is a third party service I don't control, so I can't do anything about it. That said, I'm working on an commercial replacement option since for Fenix 3 (preview.feniixwebserver.com, not available for Windows quite yet). This seems to happen alot during the US holiday season with Localtunnel.
