### ISSUE TITLE
Auto reload

### ISSUE THREAD

**Issue by estebanpadilla** [coreybutler/fenix#94]
Hello Corey, first of all thank you so much for this tools, it's awesome.
I'm wondering if you ever think of adding a auto reload feature so when you are working a site you can see the changes without clicking the reload button on the browser?

Greetings

**Comment by coreybutler** [comment]
Glad you like it!

Our roadmap for the PRO version of Fenix 3 (preview.fenixwebserver.com/https://docs.fenixwebserver.com/) has a feature like this. Instead of just focusing on live reload, we're creating an event system and some built-in autoresponders. For example, when a file changes, _one possible_ response is to auto-reload the page (as you suggested). We've had ideas for other kinds of responders too, so we're hoping to make it a pluggable system (i.e. use a built-in responder or write your own).

**Comment by coreybutler** [comment]
Closing as "answered".
